name: docker build and test

on:
  push:
    branches:
      - add_docker_file

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '[:upper:]' '[:lower:]' | tr '[:punct:]' '_')"
      id: extract_branch

    - name: Build image
      id: build-image
      env: 
        IMAGE_TAG: "${{ steps.extract_branch.outputs.branch }}"
      run: |
        docker build --no-cache -t $IMAGE_TAG .
    
    - name: Run and test image
      id: test-image
      run: |
        docker run -it $IMAGE_TAG pytest 

