name: testing - main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os}}

    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '[:upper:]' '[:lower:]' | tr '[:punct:]' '_')"
      id: extract_branch

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Install dependencies
      run: |
        pip install torch==1.13.1
        pip install -e .
        pip install -e .[tests]

    - name: Build htpmd
      run: |
        python setup.py install

    - name: pytest
      run: |
       pytest htpmd --color=yes --cov=htpmd --cov-config=.coveragerc --cov-report html:coverage_reports
