name: Linting

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting tools
        run: |
          pip install pycodestyle
          pip install flake8
          
      - name: pycodestyle
        run: |
          pycodestyle htpmd
                  
      - name: flake8
        run: |
          flake8 --count --show-source --statistics htpmd
