name: Test PR - Windows

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        os: [windows-latest]
        python-version: [3.6]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: htpmd
          environment-file: env.yml
          python-version: 3.6
          auto-activate-base: true
      
      - shell: pwsh
        run: |
          conda install mkl=2018
          conda install pytorch-geometric -c rusty1s -c conda-forge
          conda info
          conda list

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: pwsh
        run: |
          conda config --append channels conda-forge
          conda install --file=requirements.txt --file=requirements-test.txt
          pip install -e .[tests]

      - name: pytest
        shell: pwsh
        run: |
          conda install pytest
          pytest htpmd --color=yes --cov=htpmd --cov-config=.coveragerc --cov-report html:coverage_reports

      - name: Coveralls
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls
