name: Test PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          auto-activate-base: true

      - shell: bash -l {0}
        run: |
          conda install mkl=2018
          conda install pytorch==1.8.1 cpuonly -c pytorch
          conda install pyg -c pyg -c conda-forge
          conda install -c conda-forge mdtraj
          conda info
          conda list

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
          pip install -e .
          
      - name: pytest
        shell: bash -l {0}
        run: |
          conda install pytest
          pytest --color=yes --cov=htpmd --cov-config=.coveragerc --cov-report html:coverage_reports htpmd

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls
